### ISSUE TITLE
Multi-line in lists

### ISSUE THREAD

**Issue by eketorp** [Lundalogik/lime-elements#1038] opened 2020-11-13 13:49 UTC
## New feature motivation

Sometimes the user needs more information than what can be shown in a single-line header and subheader.

## New feature description

Add multi-line support for list view. Especially for sub-heading

**Comment by Kiarokh** [comment] 2020-11-19 14:52
This improvement can immediately be used in search results of global search. There, in the old angular components, we can display several lines of text. 

This was also one on the road blocks when we tried to rewrite the global search. I don't find the issue though to link it :/

**Comment by Kiarokh** [comment] 2021-04-14 12:40
duplicate of https://github.com/Lundalogik/crm-feature/issues/1212 thus will close

**Closed by Kiarokh** 2021-04-14 12:40 UTC
Labels: visual design
