### ISSUE TITLE
Limel-input-field: Out of sync changes

### ISSUE THREAD

**Issue by JohannesHansen** [Lundalogik/lime-elements#1425] opened 2021-11-08 10:12 UTC
## Current behavior

Lime Go users experience that text they enter sometimes only gets partially saved. We have had a hard time reproducing it consistently, so there is unfortunately some guesswork in this ticket. Any help investigating would be appreciated!

This issue is more likely to happen when inputing longer text content (more than a sentence), resulting in that the entered value only gets partially updated. It appears like the change event in limel-input-field either stops firing or contains an outdated value, maybe due to a buggy debounce? The displayed value will however not reflect this and appear complete. This is likely due to the "uncontrolled" nature of the input fields - the text in the input field doesn't always match the supplied value attribute.

## Environment

- **lime-elements** version: 33.12.0
- Framework used: React

**Comment by adrianschmidt** [comment] 2021-11-08 10:34
We've had issues with this too. Last I can remember, we had managed to "resolve" (a real fix would belong inside the component, I assume…) the issue in the Lime CRM Web Client (at least where we use it in the "core" web client, I'm not sure about usage in add-ons), but it still existed in Lime Admin. 

I think it ought to be a priority to find a proper fix for this…

cc @blombergedvin

**Comment by JohannesHansen** [comment] 2021-12-16 08:41
I would like to point out that this causes frequent and quite severe issues for Go users.

**Comment by adrianschmidt** [comment] 2021-12-16 08:52
> I would like to point out that this causes frequent and quite severe issues for Go users.

I don't think I can reproduce this error. Perhaps you and I can have a look at how you are using the input fields in Lime Go? Or can you make a minimal example reproducing this, that I can run without having to run the whole of Lime Go on my computer?

**Comment by DavidAkkerman** [comment] 2023-06-01 08:31
@adrianschmidt  I am having similar problems in Lime CRM. Especially when using hotkeys to save, I sometimes notice that I'm missing the last letters/words. For me it doesn't make a difference if it's a long text or only a few characters. 
To reproduce, go to the webclient (e.g. Sublime), create a history note, and when you're done typing, immediately press Ctrl+Enter to save. Most likely the last bit of text will not be saved.

**Comment by adrianschmidt** [comment] 2023-06-01 09:45
> @adrianschmidt I am having similar problems in Lime CRM. Especially when using hotkeys to save, I sometimes notice that I'm missing the last letters/words. For me it doesn't make a difference if it's a long text or only a few characters. To reproduce, go to the webclient (e.g. Sublime), create a history note, and when you're done typing, immediately press Ctrl+Enter to save. Most likely the last bit of text will not be saved.

Ah… that's unfortunate… 😞

That's probably caused either by latency in the system, or by us throttling the change events (I'm not sure we do that, but I think we might).

That seems like something that might be difficult, but quite important, to fix… 😬

Ping @eketorp FYI

**Comment by DavidAkkerman** [comment] 2023-11-10 10:00
Will anything be done with this issue? I still frequently run into this, and I don't always notice it right away, sometimes I just have missing information. 
Is this not reported by customers? In my experience it is only an issue when using keyboard shortcuts for saving. So if this is not a frequently reported issue, I guess not many people are using the keyboard shortcuts? I do think they save a lot of time, so I would like to be an advocate for using them more, but it feels dangerous as long as this issue is not resolved.

In case it's useful in tackling the issue, I have noticed something. If creating new cards, this happens frequently, when tapping Ctrl+Enter. If I change a single field on a card, it's not too much of an issue, because the save button appears only when changes are already detected, and if you're typing fast enough, my entire change is detected as 1 single change (is that what you meant with throttling Adrian?). If I hist Ctrl+S before the save button is visible, my browser tries to just save the web page, which is not ideal, but also not a big problem. However, if I have changed multiple fields, the save button is already there, so I run into the same problem as when creating a new object.

I would really like to hear your reflections @eketorp

**Comment by adrianschmidt** [comment] 2023-11-10 14:22
@DavidAkkerman I actually used the wrong term. I meant "[debounce](https://lodash.com/docs/4.17.15#debounce)", not "[throttle](https://lodash.com/docs/4.17.15#throttle)". They are similar functions though. And yes, the fact that we debounce the change event means that every time you change the value, we wait for 300 ms before we emit the change-event, in case you keep making rapid changes. If another change happens during that time, we wait for another 300 ms, and so on.

**Comment by eketorp** [comment] 2023-11-10 14:48
> Is this not reported by customers? 
It does not reach me, at least.

> So if this is not a frequently reported issue, I guess not many people are using the keyboard shortcuts?
Sounds like a fair guess. 

So I would say that we (unfortunately) have bigger issues on our plate.

**Comment by eketorp** [comment] 2023-12-08 08:02
I received this issue 

https://github.com/Lundalogik/lime-elements/assets/58422324/357584ce-1467-4f16-bb26-02d0de443c24


https://github.com/Lundalogik/lime-elements/assets/58422324/835cf185-f66e-4c82-8d0a-6c718dcfbb01

**Comment by eketorp** [comment] 2024-04-03 09:49
This is great news! Is this is line with the findings I've made so far?

1. The bug manifests itself in such a way that if you stand in the middle of a text field and type with a specific interval, the cursor can jump to the end of the field. If you are at the end of the field, the bug presents itself by causing you to lose the last typed letter.
2. The bug occurs in text fields on cards, in Lime Admin, and in packages such as Com Flow.
3. DISPROVEN: It only happens once per field. Therefore, we have not managed to make the cursor jump twice in the same field without saving in between.
4. DISPROVEN: It only occurs in conjunction with the buttons on the card. [X] [Save] is activated.
5. The issue can only be reproduced a limited number of times (two?). After that, a hard refresh and cache clearing are required to reproduce it again. This sounds completely unreasonable, but these are my observations.
6. It is not related to Heap (those small tracking GIFs that we send, like `h?a=375118334&u...`). I tested turning it off, but I could still reproduce the bug.

**Comment by vicgeralds** [comment] 2024-04-03 11:26
> This is great news! Is this is line with the findings I've made so far?

I think so. It's difficult to say exactly what conditions cause it, but slow rendering makes it more likely that the previous emitted changed value is rendered just after you start typing again.

**Comment by eketorp** [comment] 2024-04-03 13:49
I would love to try this out asap. I have a list of customers who feel the same.

**Comment by vicgeralds** [comment] 2024-04-03 14:18
> I would love to try this out asap. I have a list of customers who feel the same.

https://lundalogik.github.io/lime-elements/versions/PR-2869/#/component/limel-input-field/
https://lundalogik.github.io/lime-elements/versions/PR-2869/#/component/limel-form/

🙂

**Comment by eketorp** [comment] 2024-05-07 09:11
this one @blombergedvin

**Closed** 2024-05-14 17:52 UTC
Labels: bug
