### ISSUE TITLE
collapsable section

### ISSUE THREAD

**Issue by sofiehelgesson** [Lundalogik/lime-elements#1054] opened 2020-12-01 14:19 UTC
## Current behavior
I added a collapsable section in my dialog and it displays correct and I can expand it, but when I try to close the section the whole dialog closes. Is this a bug or am I doing something wrong?

<limel-dialog
                open={this.isOpen}
                onClose={this.closeDialog}
                heading={heading}
                class={classNames}
                closingActions={{ escapeKey: false, scrimClick: false}}
            >
                <limel-input-field
                    label="coworker"
                    value={this.coworker ? this.coworker.name : this.currentUser.fullname}
                    disabled={true}
                />
                <limel-date-picker
                    type="date"
                    format="YYYY-MM-DD"
                    label="Date"
                    value={this.date}
                    onChange={this.handleDateChange}
                    required={true}
                    invalid={!this.dateValid()}
                />
                <limel-input-field
                    required={!this.existingTimereport}
                    disabled={this.existingTimereport}
                    label="Specification"
                    value={this.specification}
                    onChange={this.handleSpecificationChange}
                    invalid={!this.specificationValid()}
                />
                <div>
                <limel-collapsible-section header="Related">
                    <limel-input-field
                        label="company"
                        value={this.company ? (this.company.name ? this.company.name : this.company.text) : null}
                        disabled={true}
                    />
                    <limel-input-field
                        label="Project"
                        value={this.project ? (this.project.name ? this.project.name : this.project.text) : null}
                        disabled={true}
                    />
                    <limel-input-field
                        label="Projectactivity"
                        value={this.projectactivity ? (this.projectactivity.name ? this.projectactivity.name : this.projectactivity.text) : null}
                        disabled={true}
                    />
                </limel-collapsible-section>
                </div>
                <limel-select
                    label="Type"
                    value={this.selectedType}
                    options={this.types}
                    onChange={this.handleTypeChange}
                    required={true}
                />

                <limel-flex-container justify="end" slot="button">
                    <div class="btn-group">
                        <limel-button
                            label="Cancel"
                            onClick={this.closeDialog}
                        />
                        <limel-button
                            label={this.existingTimereport ? "Update" : "Create"}
                            primary={true}
                            disabled={!this.valid()}
                            onClick={async () => {
                                this.saveTimereport();
                            }}
                            loading={this.loading}
                        />
                    </div>

                </limel-flex-container>
            </limel-dialog>,

## Environment
- **lime-elements** version: 28.4.3

**Comment by adrianschmidt** [comment] 2020-12-01 14:35
It's per design.

The thing is that the collapsible-section emits an event called `close`, to make it possible for the consumer (you) to know when the section was closed, in case you need to do something when that happens (although, usually you don't since collapsible-section can handle its own state).

The dialog also emits an event called `close`, for the same reason. But in the case of dialog, you are almost certainly listening to that event, and closing the dialog when you receive it. Which is the normal way of using limel-dialog, because it can't handle its own state, because the trigger has to reside outside the dialog itself.

So the problem is simply that the dialog is "hearing" the `close`-event emitted by the collapsible-section. To fix this, just add an `onClose`-callback to the collapsible-section, and stop the event in it. Something like this:

```
constructor() {
    this.handleSectionClose = this.handleSectionClose.bind(this);
}

public render() {
	return (
		<lime-collapsible
			onClose={this.handleSectionClose}
		/>
	);
}

private handleSectionClose(event: Event) {
	event.stopPropagation();
}
```

**Closed** 2020-12-01 14:38 UTC
