### ISSUE TITLE
Dialog footer is rendered for empty slot button

### ISSUE THREAD

**Issue by anderssonjohan** [Lundalogik/lime-elements#1009] opened 2020-10-30 08:37 UTC
## Current behavior

When you don't give a `<limel-dialog/>` something for its slot `button`, it will still render a empty footer making the dialog look bad.

<img width="373" alt="Screenshot 2020-10-30 at 09 31 06" src="https://user-images.githubusercontent.com/435885/97677554-b9390000-1a92-11eb-90b9-a97482ef4dc2.png">
<img width="363" alt="Screenshot 2020-10-30 at 09 26 54" src="https://user-images.githubusercontent.com/435885/97677557-ba6a2d00-1a92-11eb-8aa5-117bbe5c5962.png">

## Expected behavior

The footer should not render when the slot is empty.

Example with the `<footer/>` deleted in the browser:
<img width="421" alt="Screenshot 2020-10-30 at 09 31 18" src="https://user-images.githubusercontent.com/435885/97677636-d8379200-1a92-11eb-98f8-3c09c2651d24.png">

Maybe something like this would work to check for the empty slot?

```
componentWillLoad() {
    this.hasButtonSlot = !!this.host.querySelector('[slot="button"]');
...
}
```

```
   {if(this.hasButtonSlot){ }
   <footer class="mdc-dialog__actions">
       <slot name="button" />
   </footer>
   {}}
```

## Environment

- **lime-elements** version: 29.1

**Comment by adrianschmidt** [comment] 2020-10-30 08:57
What's the use-case for not having even a button to close the dialog?

I'm not sure it's a good idea to show a dialog that requires the user to know that they can close it by clicking outside it or pressing escape.

@Kiarokh thoughts?

**Comment by anderssonjohan** [comment] 2020-10-30 09:30
@adrianschmidt If you do a fullscreen image viewer that closes the dialog on click, it's perfectly fine to ditch the `<footer/>` IMHO. In my case it's for mobile device adaption. Having the buttons in the footer is really bad on a mobile, hence why we put actions like that in the header. Example of such design: https://uigarage.net/compose-on-android-by-gmail/

The following is just based on a mockup from our PM @eketorp, but with the same intentions: Don't hide the buttons underneath the on-screen keyboard.

<img width="369" alt="Screenshot 2020-10-30 at 10 25 08" src="https://user-images.githubusercontent.com/435885/97688558-901c6d80-1a9a-11eb-8433-fc73a9cf3608.png">

In the example above we used multiple buttons in the header but I'm into replacing the cancel button with a left arrow icon button in the top left of the dialog, just like in the Gmail compose dialog example linked above.

**Comment by adrianschmidt** [comment] 2020-10-30 09:55
@anderssonjohan Ah, ok, I understand 👍

What's the reason you think buttons in the footer are bad on mobile? Is it only because the keyboard will show up at the bottom, or are there other reasons? Buttons at the top are harder to reach, but maybe that's the point, to make it harder to touch them accidentally?

**Comment by Kiarokh** [comment] 2020-10-30 10:53
Oh boy 😄 yet another reason why modals come with inherent problems by the way…

> What's the use-case for not having even a button to close the dialog?

Good question Adrian. But I don't have a good spontaneous answer. I can imagine that there might be a use-case, in certain conditions. And if that happens, the bar shouldn't be there. In other words, if there are no buttons down there, the bar shouldn't be there neither (what's the point of an empty bar anyways?). Will this happen in reality with a legitimate use? Hm.... probably...

--------

> Having the buttons in the footer is really bad on a mobile, hence why we put actions like that in the header.

This question is really hard to answer with a universal answer, because modals are !"#@ pieces of 💩.

Generally, I'm not sure if placing actions on top **on mobile phones** provides a good UX. It can sometimes be against [the guideliens](https://material.io/components/app-bars-bottom#anatomy). 

When phones tended to be smaller, apps used to put their action bars on top. With taller phones being very common nowadays (and honestly even on smaller devices), having actions on top edge makes them slightly inaccessible for the users, as most of the interactions are taking place using thumbs. Thumbs don't reach top of the screen that easily. Specially because users usually use one hand to interact with the device. 

<img width="29%" src="https://user-images.githubusercontent.com/35954987/97691192-53527580-1a9e-11eb-80d9-63c037a8d8e4.png"/><img width="69%" src="https://user-images.githubusercontent.com/35954987/97691219-5d747400-1a9e-11eb-907e-54caf3a03b47.png"/>

Thus contemporary designs for action bars are turning like this:
![image](https://user-images.githubusercontent.com/35954987/97691447-ad533b00-1a9e-11eb-889d-020508039b54.png)
![image](https://user-images.githubusercontent.com/35954987/97691499-bba15700-1a9e-11eb-873c-d29eedb01d8e.png)
and top bars are becoming places for showing contextual info, such as tabs, breadcrumbs, titles, etc..

But do they really?

Material design is a mess of inconsistencies. [Check this out…](https://material.io/components/app-bars-top#usage)
![image](https://user-images.githubusercontent.com/35954987/97693642-c3aec600-1aa1-11eb-9d4c-4aff5ee9213b.png)
![image](https://user-images.githubusercontent.com/35954987/97693825-02dd1700-1aa2-11eb-866a-c6b768fcb33b.png)

So what do we do with

> Don't hide the buttons underneath the on-screen keyboard.

If **bottom action bars** exists, *only them* shouldn't be rendered below the keyboard or be cut-off by the keyboard, but the entire bottom part of the modal should be covered by the keyboard. When keyboard is opened, the action bar or whatever else is in the screen is inferior to it.

[Guidelines…](https://material.io/components/app-bars-bottom#behavior)
![image](https://user-images.githubusercontent.com/35954987/97694156-767f2400-1aa2-11eb-8442-45d32900dcc7.png)


**Note!** Two things make answering this question a hell:
1. We are making a responsive design (not adaptive) which should both work on phones and desktops. As mentioned earlier and both of you have read it, this is really bad in itself. But we have no choice for now.
1. We are discussing these inside #@!%ing modals, not fullscreen views. Modals on phones are not usual things and shouldn't be. You usually won't open a modal with such extensive functionalities as you illustrate in your example picture above @anderssonjohan. On a phone, you'd go to a fullscreen view for that. (And you also must question your choice here. Is opening a modal the only way to address your need?)


Anyhow, in the picture above, you see that there is a contextual action bar
![image](https://user-images.githubusercontent.com/35954987/97695091-ca3e3d00-1aa3-11eb-8dda-fda9595a9e0a.png)

You could perhaps argue that this in you design is also a "contextual action bar", thus it can be placed on top.
![image](https://user-images.githubusercontent.com/35954987/97695175-ef32b000-1aa3-11eb-88c8-46109a405a25.png)

But I feel it isn't, really… and you shouldn't put a contextual action bar on top of tab bars. I don't know whether choice of tabs is good here, because I don't know what you wanna do in this design :) But if you wanna use a contextual actionbar, you should perhaps consider switching the tabs and using [collapsible sections](http://lime-documentation-lime-elements.s3-website-eu-west-1.amazonaws.com/versions/29.1.0/#/component/limel-collapsible-section) (??). Having a contextual action bar should be OK below/inside each tab (which means only saving things inside the active tab).

What's a contextual actionbar? 
It's a bar that appears when it makes sense or its respective actions are needed, otherwise it doesn't exist. For example, when you make a change, the **discard** and **save** buttons appear (context has changed, and you need these actions now).

# Conclusion 

In modals, I still think we should put the action bar at the bottom, to make it easier for thumbs to reach the buttons. We should keep in mind that modals are NOT and should NOT represent a fullscreen view/pane. Actions you put in them should be simple. 

I don't think we can or should shrink the modals when the keyboard is opened on mobile devices to be able to display the modal's actionbar above the keyboard. This makes other things harder, and makes usage of modals on small screens or landscape mode worse than what it already is.

**Comment by Kiarokh** [comment] 2020-10-30 11:11
I wrote some guidelines for using tabs in Lime Elements. Not sure why they are not showing up currently in the documentations. But here they are, until we fix this issue: https://github.com/Lundalogik/lime-elements/pull/877/files#diff-da32d804537a409d766985b357966bef012b60640ee9004de781b8cf3b744c9f

Check out the changes in `tab-bar.mdx`.

**Comment by eketorp** [comment] 2020-10-30 11:39
Thanks for all the input! The reason why I dislike buttons at the bottom is because I've used it throughout CRM on mobile and don't like it. In fact, I hate it. Constantly, I have to minimize my keyboard to see the save button and that is a bigger problem than having to reach to the top of the screen, I would say. This has been proven when using CRM on a phone (which I seem to be the only one doing). Phones have all become so big that they're already impossible to use with one hand.

And on cards, we put the save button at the top right, so aren't we arguing against ourselves here?

I know everyone who loves good design loves to hate modals (and dropdows). Personally, I think the modal isn't that bad in this user case. If we were to use a tab on the card instead we would lose lots of pixels and it would be a very strange behaviour, considering other aspects.

So why do we suggest using a modal in this case?
- Focus. Stay until you're done and click Save.
- Ability to use a large part of the screen.
- Don't lose context. Easy to see where I came from and how to get back.

**Comment by eketorp** [comment] 2020-10-30 11:48
Collapsible sections instead of tabs isn't a completely bad idea. But it forces the user to scroll. Which they don't. A lot of people don't know when to scroll. Sad but true.

**Comment by adrianschmidt** [comment] 2020-10-30 11:56
> Constantly, I have to minimize my keyboard to see the save button

Bluärgh! I assume that's on an iPhone? 😭

I would consider that a bug in the phone. This is how it's meant to work:

![image](https://user-images.githubusercontent.com/154725/97702308-12169180-1aaf-11eb-8f0e-84398f38f26b.png)

But yeah, if it works like crap on iPhone, while that certainly *should* be Apple's problem, reality is of course that it's *our* problem… 🤬 😢

**Comment by adrianschmidt** [comment] 2020-10-30 12:09
> Collapsible sections instead of tabs isn't a completely bad idea. But it forces the user to scroll. Which they don't. A lot of people don't know when to scroll. Sad but true.

Do you actually have data on that? Because I remember reading a report from Nielsen which said their research found no truth to the claim that people don't scroll.

That was over ten years ago, and things may have changed. The trend of not displaying scrollbars unless scrolling surely isn't helping, but on the other hand, it's kind of hard to imagine that users on average are *less* computer savvy now than they were ten years ago?

If it's a matter of people not understanding that there's something to scroll *to*, then that's a different matter, and something we should certainly address in our design.

**Comment by eketorp** [comment] 2020-10-30 12:12
It’s an iPhone but I don’t think the problem is the phone. The behaviour you show only seem to work when creating new line records. All other modals behave differently. 

And even if they would, I still don’t think it’s great behaviour in this case where you more or less run a time reporting app rather than an input form.

**Comment by Kiarokh** [comment] 2020-10-30 12:27
I see your points @eketorp and you're right. Not having a place in the CRM that gives you a fullscreen view to utilize may be a design problem at its core, that we have now. But when you go to the roots of it, it boils down to having a responsive design with responsive components that should work on phones too. This means, we are forced to do trade-offs, which in your case means using a modal perhaps. (As I said, I don't know what you wanna do, so I don't say it's wrong or right). Anyhow, we should try to see whether we can find a navigation pattern that addresses the need that you and many others have in this case.

But if you have to use a modal with contextual actions, and tabs, you must put those actions inside each tab. 
> And on cards, we put the save button at the top right

If you mean the save button that today is located in header and saves the tweaks in the "overview" tab, [it's moved inside the tab now](https://github.com/Lundalogik/crm-feature/issues/1044). It was up there just because of technical difficulties and AngulaJS components and such.

Regarding Adrian's latest screenshot on Android:
This solution works only on portrait mode. I guess in landscape mode this makes the UI pretty much unusable. But there in the picture, even the app's bottom bar is above the keyboard. It seems Android has chose to shrink the entire viewport when the keyboard is opened. So I don't know what to say.

> A lot of people don't know when to scroll. 

This is a classic 😄 There has been a lot of discussions about it. I have chosen to strongly disagree. For the simple fact that you cannot possibly design any dynamic user interface for all screen sizes and device, that makes sure that all people will always see everything at any give UI and screen. [Nice experiemt](https://iamthefold.com/). Additionally, people will scroll when they feel they have to. There might be some unfortunate cases sometimes imposed by bad design, sometimes unavoidable. So in those cases, you may not guess that you have to scroll. But that's it. That can even happen inside a tab. This is an impossible challenge to solve, so it shouldn't be given too much wight when designing. However, when a UI can hint for scroll possibilities, it should do. Like the shadow effects that we have in the modal to indicate there is some content below what you see. This doesn't [work perfectly though](https://github.com/Lundalogik/crm-feature/issues/1039#event-3928287004), but the issue was close :( .

I've also seen any studies that people scroll. And noticed that people sometimes instinctively scroll just to make sure there is nothing left that they may be missing.

**Comment by Kiarokh** [comment] 2020-10-30 12:31
I'd like to revise my conclusion:

# Conclusion 

In modals, I still think we should put the action bar at the bottom, to make it easier for thumbs to reach the buttons. We should keep in mind that modals are NOT and should NOT represent a fullscreen view/pane. Actions you put in them should be simple. 

I don't think we can or should shrink the modals when the keyboard is opened on mobile devices to be able to display the modal's actionbar above the keyboard. This makes other things harder, and makes usage of modals on small screens or landscape mode worse than what it already is.

When the modal's bottom bar (footer/actionabar) is empty, it shouldn't tak space.

We should investigate adding a new functionality to the modal's header, to present contextual actions, or simply render action buttons on top.

**Comment by adrianschmidt** [comment] 2020-10-30 12:44
> I don't think we can or should shrink the modals when the keyboard is opened on mobile devices to be able to display the modal's actionbar above the keyboard. This makes other things harder, and makes usage of modals on small screens or landscape mode worse than what it already is.

We shouldn't and we can't. That's up to the browser or the device, or whatever it is that decides the size of the viewport.

**Comment by eketorp** [comment] 2020-10-30 12:49
Good discussion!

> Do you actually have data on that? Because I remember reading a report from Nielsen which said their research found no truth to the claim that people don't scroll.
It's just my own data from doing user tests. I know we don't do user tests here at Lime but I did those when working for another employer ;). Jokes aside, of course a lot of people scroll but when doing user tests, I've been surprised about how many don't scroll. 

Like Kia said, this can be avoided (to some extent) with good design but it's not as good as not having to scroll.

> Modals are NOT and should NOT represent a fullscreen view/pane. Actions you put in them should be simple.
I think we're adressing an interesting problem: small apps within CRM. This isn't just an input form. It's a small app. In other cases it might be a guide. Should they be presented differently? Fullscreen? Maybe. Maybe not. However, if this is to be solved, it's a hell of a lot bigger design task than the heading of this issue :). Or do you have a good solution @Kiarokh ?

Regarding having save buttons within each tab: I see your point. But you need to see the full application in order to understand why that's probably not a great idea in this user case. What you save is actually not what's under each tab, but what's in the cart next to the save button. But... maybe tabs aren't the best solution here. The design started out as "I definitely don't want tabs" but that's the best solution I could figure out.

**Comment by anderssonjohan** [comment] 2020-10-30 13:55
> > Constantly, I have to minimize my keyboard to see the save button
> 
> Bluärgh! I assume that's on an iPhone? 😭
> 
> I would consider that a bug in the phone. This is how it's meant to work:
> 
> ![image](https://user-images.githubusercontent.com/154725/97702308-12169180-1aaf-11eb-8f0e-84398f38f26b.png)
> 
> But yeah, if it works like crap on iPhone, while that certainly _should_ be Apple's problem, reality is of course that it's _our_ problem… 🤬 😢

An example of iOS and limel-dialog:
<img width="394" alt="Screenshot 2020-10-30 at 14 31 17" src="https://user-images.githubusercontent.com/435885/97711165-05009f00-1abd-11eb-8cdb-b8fa5f224d5d.png">

This is a dialog using the button slot but they're hidden because the dialog is rendered inside the parent view's details tab on iOS.

Here's another example, not related to the dialog, hiding the important progress because of the on-screen keyboard hiding the login progress.

Android:
![login-no-feedback](https://user-images.githubusercontent.com/435885/97711545-848e6e00-1abd-11eb-9328-53c5e9ca4f2f.gif)
iOS:
<img width="369" alt="Screenshot 2020-10-30 at 14 08 06" src="https://user-images.githubusercontent.com/435885/97712443-b9e78b80-1abe-11eb-99b6-64fffcf6ccee.png">

This is why our 2010 version of the Lime Field login still sticks around in that old mobile app, because it dogdes the on-screen keyboard without the need of scrolling the view/refocusing when tapping the inputs. Our newer apps have the same issue due to the same design as in CRM - wasting all pixels on the logo+message.
My simple fix to such issue is placing the icon+message in a top bar just like in the old login screen.
<img width="736" alt="Screenshot 2020-10-30 at 14 48 38" src="https://user-images.githubusercontent.com/435885/97712962-73466100-1abf-11eb-8f21-7dddb92ab938.png">


@kiarokh @adrianschmidt Btw, we don't want to use a dialog here. We are misusing the dialog to build views. IMHO you shouldn't be using input elements at all in dialogs. The behavior you screenshoted @adrianschmidt is correct, but you shouldn't have the on-screen keyboard pop up when a dialog shows. Then you end up in this kind of UI:

<img width="744" alt="Screenshot 2020-10-30 at 14 20 22" src="https://user-images.githubusercontent.com/435885/97712161-5f4e2f80-1abe-11eb-9353-c0f32219a4bb.png">

**Comment by anderssonjohan** [comment] 2020-10-30 14:36
> I see your points @eketorp and you're right. Not having a place in the CRM that gives you a fullscreen view to utilize may be a design problem at its core, that we have now. But when you go to the roots of it, it boils down to having a responsive design with responsive components that should work on phones too. This means, we are forced to do trade-offs, which in your case means using a modal perhaps. (As I said, I don't know what you wanna do, so I don't say it's wrong or right). Anyhow, we should try to see whether we can find a navigation pattern that addresses the need that you and many others have in this case.
> 
> But if you have to use a modal with contextual actions, and tabs, you must put those actions inside each tab.
> 
> > And on cards, we put the save button at the top right
> 
> If you mean the save button that today is located in header and saves the tweaks in the "overview" tab, [it's moved inside the tab now](https://github.com/Lundalogik/crm-feature/issues/1044). It was up there just because of technical difficulties and AngulaJS components and such.
> 
> Regarding Adrian's latest screenshot on Android:
> This solution works only on portrait mode. I guess in landscape mode this makes the UI pretty much unusable. But there in the picture, even the app's bottom bar is above the keyboard. It seems Android has chose to shrink the entire viewport when the keyboard is opened. So I don't know what to say.
> 
> > A lot of people don't know when to scroll.
> 
> This is a classic 😄 There has been a lot of discussions about it. I have chosen to strongly disagree. For the simple fact that you cannot possibly design any dynamic user interface for all screen sizes and device, that makes sure that all people will always see everything at any given UI and screen. [Nice experiemt](https://iamthefold.com/). Additionally, people will scroll when they feel they have to. There might be some unfortunate cases sometimes imposed by bad design, sometimes unavoidable. So in those cases, you may not guess that you have to scroll. But that's it. That can even happen inside a tab. This is an impossible challenge to solve, so it shouldn't be given too much wight when designing. However, when a UI can hint for scroll possibilities, it should do. Like the shadow effects that we have in the modal to indicate there is some content below what you see. This doesn't [work perfectly though](https://github.com/Lundalogik/crm-feature/issues/1039#event-3928287004), but the issue was close :( .
> 
> I've also seen any studies that people scroll. And noticed that people sometimes instinctively scroll just to make sure there is nothing left that they may be missing.

Whoa, sorry if this generated a lot of heat :) 
YES - We are so much trying to abuse the mdc dialog to build (fullscreen) views, that's for sure.
Here's what the view-ish thing looks right now:
<img width="362" alt="Screenshot 2020-10-30 at 14 22 52" src="https://user-images.githubusercontent.com/435885/97715159-58c1b700-1ac2-11eb-970f-3bf21e7f61a3.png">
(it's also expected to use a wider dialog, covered by #1006)

It's basically following along with many existing apps like this example from MS Teams with the top action bar and the stretched tabs.

![Microsoft-Teams-Android](https://user-images.githubusercontent.com/435885/97715073-3d56ac00-1ac2-11eb-8856-9ecadcdcf859.jpg)

The use case here is like @eketorp described, it's a workflow similar to what you have in the related tabs in CRM where you create one lime object at the time and leave the dialog on each create. This "dialog" implements a behavior where you continue adding stuff until you're done and saves all the lime objects and close the dialog when you click save.

In our previous versions of this we used a combination of tabs + accordions just like in this example.
When only using accordions it can of course increase the need of scroll, just like in the following example.
IMHO, accordions doesn't add much more than being headings of sections.

![button-should-say-save-android](https://user-images.githubusercontent.com/435885/97716188-9d018700-1ac3-11eb-9f72-79eb746e1561.gif)

If we get back to this issue, if we only are meant to use the limel-dialog for alerts and such (as I wrote earlier, IMHO you should not put inputs in a dialog used on mobile) I do think it's reasonable to require the button slot. But if it's meant to be used for much more things, like doing a pop-up map, image/video/document viewer with a top toolbar etc, I do think we need to be able to customize the limel-dialog to a greater extent.

**Comment by Kiarokh** [comment] 2020-10-30 15:00
> an interesting problem: small apps within CRM.

>  However, if this is to be solved, it's a hell of a lot bigger design task than the heading of this issue :). Or do you have a good solution @Kiarokh ?

Yes, we exactly have this problem Tomas! And right now I don't have a good solution. The furthest we have gotten so far is the concept of "custom tabs" – as folks call it internally.

I had addressed this exact issue in my first design sketches which got the title of the "big bang", and scared off everyone. There, I have solutions for these small apps. But due to the way we work (or more fairly said, "have to work"), it will take a good while until we get there. 

CRM suffers fundamental design problems in a bigger scales, such as the ones you guys are struggling with. There is no decent navigation paradigm, and everything traditionally has been treated as bloody "tables" (with an exception of the todo widget perhaps). 

Anyhow, we had to start with the "Object card"; and in the object cards, we can't address those bigger issues.

For now, either we have to stick to modals, or use the tabs. But soon, those "Global table views" will go to hell! 😄 and instead of them, we will have app-lunchers. That entry point will let you choose apps, instead of "global tables". And in there, you can do fullscreen apps in their full glory 🎉 and don't have to abuse the modals.


-----

I guess the quickest and most pragmatic solution for now is that:

* you guys @eketorp @anderssonjohan keep your contextual buttons on top and test a new UI with collapsible section if you want. Or keep your tabs. That's not a catastrophe I mean. They work, even if it's an unconventional UI.  

* And we have to get rid of the bottom bar of modals that is empty, but keeps occupying space. 

* We can't solve the iOS way of rendering things below the keyboard, versus Android's way of shrinking the viewport. Even if we could, there would always be some distributers of Android (Xperia, Huawei, etc..) who override Android's way of doing stuff, and contribute to the hell of modal-usage, along with other craps.

* But we should see if we can smartly offer a top bar or header for modals, which could include actions. This also requires more thoughts.

**Comment by anderssonjohan** [comment] 2020-10-30 15:39
@Kiarokh Then I'll try to squeeze in some PRs with these small additions. I have a couple of very small issues posted in this repo that I can contribute PRs for and then we can take each from there.
Until then, we can always use our own dialogs/branches of this repo, etc.

Regarding the issue with the dialog not being rendered correctly (inside the scroll area of the details tab) on iOS may have a reasonable cause. I just noticed that the code this was based on didn't use the dialog service at all. It rendered the dialog alongside the button that opened it, hence having it rendered inside the details tab and not in the `<lime-dialog>` element on the page.

From the component's render method:
```typescript
return [
            <limel-button
                primary={true}
                label={this.getTranslation('btn_open_dialog')}
                icon={'money'}
                onClick={() => {
                    this.isDialogOpen = true;
                }}
            />,
            <lwc-solution-workorder-add-articlerow-form-ns
                platform={this.platform}
                context={this.context}
                isDialogOpen={this.isDialogOpen}
            />
        ];
```

Although it's unfortunate this worked in chrome on desktop + android it, it's rendering in chrome on iOS is more semantically correct since the code doesn't use the dialog service to dispatch the rendering to the correct place on the page. 🎉

**Comment by Kiarokh** [comment] 2020-11-02 07:59
> I'll try to squeeze in some PRs

@anderssonjohan it's awesome man! It's really great if everybody makes Lime Elements better and more reliable, instead of making individual custom solutions. 🎉 I even wish that custom solutions could actually become a component in Lime Elements instead (like a modal-header with action buttons, and many more).

> component's render method

🤭 

Do you mean they keyboard pushes up the modal now when the render method is fixed? 🤩 This is amazing and very interesting. It's great that you can fix this.

p.s.
This actually, makes me wonder why Android choses to shrink the viewport, when keyboard is open.

**Comment by adrianschmidt** [comment] 2020-11-02 09:31
> Until then, we can always use our own dialogs/**branches of this repo**, etc.

🤔 If you're building an add-on for Lime CRM Web Client, then the web client will provide the version of Lime Elements used. Which version or branch you install locally while developing only matters for typings and stuff like that, it doesn't affect what's run when your add-on is deployed in production.

**Comment by adrianschmidt** [comment] 2020-11-02 09:34
> > component's render method
> 
> 🤭
> 
> Do you mean they keyboard pushes up the modal now when the render method is fixed? 🤩 This is amazing and very interesting. It's great that you can fix this.

I don't think that's what he meant. I think he was referring to this issue:
<img width="394" alt="Screenshot 2020-10-30 at 14 31 17" src="https://user-images.githubusercontent.com/435885/97711165-05009f00-1abd-11eb-8cdb-b8fa5f224d5d.png">

**Comment by anderssonjohan** [comment] 2020-11-03 22:11
> > > component's render method
> > 
> > 
> > 🤭
> > Do you mean they keyboard pushes up the modal now when the render method is fixed? 🤩 This is amazing and very interesting. It's great that you can fix this.
> 
> I don't think that's what he meant. I think he was referring to this issue:
> <img alt="Screenshot 2020-10-30 at 14 31 17" width="394" src="https://user-images.githubusercontent.com/435885/97711165-05009f00-1abd-11eb-8cdb-b8fa5f224d5d.png">

This issue is now fixed at our end. It's a totally reasonable behavior of the dialog because we hosted it inside that tab and not in the "root" / closer to the `<body>` / in the proper dialog host element :)

I changed to use a proper dispatch using the dialog service in one of the dialogs and now the changed one has the correct host element.

Without dialog service: `/html/body/lime-root/lime-object-route/lime-object/lime-object/div/section/lime-object-tabs/limec-object-tab-panel/div/section[1]/lime-object-overview/limec-object-overview//div/lwc-solution-workorder-add-article//lwc-solution-workorder-add-article-form//limel-dialog` 
With dialog service: `/html/body/lime-root/lwc-solution-workorder-add-articlerow-form-ns[4]//limel-dialog`

![use-dialog-service](https://user-images.githubusercontent.com/435885/98046077-d0c50f80-1e29-11eb-9324-e9ef137c9e28.gif)

**Closed** 2020-12-23 12:15 UTC
Labels: visual design

**Comment by Kiarokh** [comment] 2021-01-07 09:31
I guess this has created a bug: https://github.com/Lundalogik/crm-feature/issues/1706
