### ISSUE TITLE
Add support for more limel input types to limel form

### ISSUE THREAD

**Issue by Kiarokh** [Lundalogik/lime-elements#760] opened 2020-05-13 07:24 UTC
Currently, the limel form does not support some of the input fields. For example you cannot have sliders in a form, or chipsets.

**Comment by magnusfagerlund** [comment] 2020-06-04 10:17
What does this issue mean? Please add more details.

**Comment by Kiarokh** [comment] 2020-06-04 13:32
> What does this issue mean? Please add more details.

Sorry. Updated both the title and the description ;)

**Comment by adrianschmidt** [comment] 2020-06-16 08:21
At the moment, we have two different issues just saying "add more", not which ones exactly. Issues like these just clog up the backlog, as they have no "definition of done". Please create one issue for each specific component that needs doing, and add a motivation for why that specific component needs doing for each. There are issue templates in this repo for a reason, please use them.

I'm closing this as a duplicate of Lundalogik/crm-feature#1130.

**Closed by adrianschmidt** 2020-06-16 08:21 UTC
