### ISSUE TITLE
dialog: not getting the shadow effect if an inserted component has a background color (like table)

### ISSUE THREAD

**Issue by LucyChyzhova** [Lundalogik/lime-elements#2090] opened 2023-01-31 12:05 UTC
## Current behavior

https://user-images.githubusercontent.com/50618208/215755026-08d1f2eb-502b-4650-94c3-3bb289265273.mov

1. …

## Environment

- **lime-elements** version: 
- Framework used: 
- Logs:

**Comment by adrianschmidt** [comment] 2023-02-17 08:21
This is a duplicate of #1998

**Closed by adrianschmidt** 2023-02-17 08:21 UTC
Labels: bug

**Comment by adrianschmidt** [comment] 2023-02-17 08:22
@LucyChyzhova Feel free to put #1998 on the Feature board instead, if you want to 🙂
