### ISSUE TITLE
`limel-form` with schema required fields breaks validations from being displayed correctly

### ISSUE THREAD

**Issue by simonedeblasio** [Lundalogik/lime-elements#3158] opened 2024-09-11 09:18 UTC
## Current behavior
If a field is required the part that displays errors in a form breaks. 

![image](https://github.com/user-attachments/assets/516527c9-031b-47eb-bc20-eecf565268bf)
Both fields here need to be larger than today, but since field 1 is set to required the error is not displayed.

If I click around like few times it is then finally displayed:
![image](https://github.com/user-attachments/assets/133ac23e-95a1-4096-bd95-59d737898c45)

If I just remove the "required" part in the schema `required: ['startdate']` it works and shows the error immediately. 

To clarify, for the field 2, it always shows the error directly and as expected. The only difference is the required part.

1. Create a dialog with form + schema. 
2. Add two fields in the schema, set one to required in the schema.
3. Add logic in the "onChange" for the form that updates the errors. For example date must be larger than today.

Like this:
``` typescript
<limel-form
    onChange={this.handleFormChange}
    value={this.formData}
    schema={getSchema(this.limetypes, this.limeobject)}
    errors={this.errors}
/>,
```

This bug might have a releated issue which is that if you pass your own errors to a form, it will still thinking something is empty even though you have filled it in:
![image](https://github.com/user-attachments/assets/7d15d821-84c4-4f3a-9c80-086a365b0724)
Even when switching between fields, still keeps saying that its required. I need type more/again in it for it to refresh the validation.

## Expected behavior

The error do be displayed right after the value was input

## Environment

- **lime-elements** version: 36.2.0

**Comment by simonedeblasio** [comment] 2024-09-11 09:19
Ping maybe @adrianschmidt or @vicgeralds

**Comment by vicgeralds** [comment] 2024-09-11 11:16
> schema={getSchema(this.limetypes, this.limeobject)}

What's happening in `getSchema`? If you create a new schema on every render, I expect that will cause problems.

Other than that, I'm not sure what might cause this. Will need to debug a bit when I get the time.

**Comment by simonedeblasio** [comment] 2024-09-11 11:24
The only logic in it is populating default values and setting readonly depning on the default values.
``` typescript
export const getSchema = (
    limetypes: Record<string, LimeType>,
    limeobject: LimeObject
) => {
    const today = new Date();
    const swedishStartdate = new Date(limeobject.startdate);
    const swedishStartdateString = getSwedishDate(limeobject.startdate);
    const swedishGraduationdateString = getSwedishDate(
        limeobject.graduationdate
    );

    return {
        type: 'object',
        properties: {
            type: {
                title: limetypes.profession_or_education.getProperty('type')
                    .localname,
                type: 'string',
                oneOf: mapOptions(
                    limetypes.profession_or_education.getProperty('type'),
                    ['empty']
                ),
                default: limeobject.type,
                readOnly: true,
            },
            person: {
                title: limetypes.profession_or_education.getProperty('person')
                    .localname,
                type: 'object',
                readOnly: true,
                lime: {
                    key: 'person',
                    component: LIME_PICKER_COMPONENT,
                },
            },
            company: {
                title: limetypes.profession_or_education.getProperty('company')
                    .localname,
                type: 'object',
                readOnly: true,
                lime: {
                    key: 'company',
                    component: LIME_PICKER_COMPONENT,
                },
            },
            startdate: {
                title: limetypes.profession_or_education.getProperty(
                    'startdate'
                ).localname,
                type: 'string',
                format: 'date',
                lime: {
                    key: 'startdate',
                    component: {
                        props: {
                            language: 'dk',
                            format: DATE_FORMAT,
                        },
                    },
                },
                readOnly: today > swedishStartdate,
                default: swedishStartdateString,
            },
            graduationdate: {
                title: limetypes.profession_or_education.getProperty(
                    'graduationdate'
                ).localname,
                type: 'string',
                format: 'date',
                lime: {
                    key: 'graduationdate',
                    component: {
                        props: {
                            language: 'dk',
                            format: DATE_FORMAT,
                        },
                    },
                },
                default: swedishGraduationdateString,
            },
        },
    };
};
```

**Comment by vicgeralds** [comment] 2024-09-11 15:13
> The only logic in it is populating default values and setting readonly depning on the default values.

It's still a new object instance created on every render, and it's a different schema when deeply compared as well. Changing the schema on every change made in the form isn't expected to work well.

**Comment by simonedeblasio** [comment] 2024-09-11 15:17
> > The only logic in it is populating default values and setting readonly depning on the default values.
> 
> It's still a new object instance created on every render, and it's a different schema when deeply compared as well. Changing the schema on every change made in the form isn't expected to work well.

This is the way schemas are used in almost all customizations for customers. We need them to be dynamic since the data is dynamic. Its never hard-coded the way the examples are in the lime-elements documentation. It generally works very well, its just this specific combination that I have found to be broken.

**Comment by vicgeralds** [comment] 2024-09-11 15:19
> lime-elements version: 36.2.0

This version is very old. There has been several fixes to both date-picker and input-field since then

**Comment by vicgeralds** [comment] 2024-09-11 15:22
> This is the way schemas are used in almost all customizations for customers. We need them to be dynamic since the data is dynamic

You don't need to change the schema _on every render_. You can create it once in `componentWillLoad` for example, or only when `limeobject` changes.

**Comment by simonedeblasio** [comment] 2024-09-12 07:42
Ah okay, did not know that, thanks!

I moved out the `getSchema` to `componentWillLoad` and upgraded to @limetech/lime-elements: '37.52.0', same as the penultimate version of lime-crm deployed to isolated applications. 

The issue still persists.

**Comment by vicgeralds** [comment] 2024-09-16 08:53
The only way I could reproduce this problem is by passing the value as `Date` (which isn't valid according to your schema, expecting a string of format "date").

There's a check that fails to detect a `Date` value as nonempty, which results in validation errors not being shown. As far as I can see, the json schema validator will always consider `Date` value as invalid, as it doesn't convert it to a string when validating (serializing it to json would convert it to a string of format "date-time").

Is it possible that you `Date` values in `this.formData`?

I'm also a bit surprised to see that you use format "date" but it looks like your schema will render date-time pickers due to this bug: https://github.com/Lundalogik/lime-elements/issues/1489

**Comment by simonedeblasio** [comment] 2024-09-17 11:49
> Is it possible that you have Date values in this.formData?

Hmm I don't think so, the only thing we ever assign this.formData.startdate is undefined or event.detail. The code is [here](https://github.com/Lundalogik/solution-socialraadgiverne-utveckling/blob/6ae764649892fd1bf8c914722572b725fd5c453a/frontend/src/components/lwc-solution-socialraadgiverne-utveckling-update-poe-dates/lwc-solution-socialraadgiverne-utveckling-update-poe-dates.tsx#L195)

> I'm also a bit surprised to see that you use format "date" but it looks like your schema will render date-time pickers due to this bug: https://github.com/Lundalogik/lime-elements/issues/1489

We are experiencing the same bug yes.

**Comment by vicgeralds** [comment] 2024-09-17 12:42
> the only thing we ever assign this.formData.startdate is undefined or event.detail

Ah, ok, that explains it. We don't display errors initially for required fields that have no value. So if you instead asssigned it the default value I think the error would be shown.

**Comment by simonedeblasio** [comment] 2024-09-17 12:47
Thats what we do though? `default: swedishStartdateString` Or am I missing something? 

We only set it to `undefined` if the user empties it, since it then otherwise would display "not valid string". This works fine for the other field that is not required.

**Comment by vicgeralds** [comment] 2024-09-17 13:15
Sorry, I mean if you assigned it a value rather than `undefined` I think it would show the error. Having a default value doesn't help if you clear the value when setting `this.formData`.

So, `this.formData.startdate = defaultStartDate` would probably work.

**Comment by simonedeblasio** [comment] 2024-09-18 12:10
Hmm not sure if I understand, could I show you during office hours tomorrow?

**Comment by vicgeralds** [comment] 2024-09-20 06:41
Ok, so I finally was able to reproduce and understand the problem. The fix that I did before solves it: https://github.com/Lundalogik/lime-elements/pull/3165

So it was a problem with detecting a Date value as empty, but the date values are converted from strings internally by the date picker widget. In other words, it was clearly a bug lime elements that caused this. 😊

**Closed** 2024-09-20 07:48 UTC
Labels: bug
